apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-db
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_NAME: {{ .Values.secretEnv.DATABASE_NAME | b64enc | quote }}
  DATABASE_USER: {{ .Values.secretEnv.DATABASE_USER | b64enc | quote }}
  DATABASE_PASSWORD: {{ .Values.secretEnv.DATABASE_PASSWORD | b64enc | quote }}
